### ISSUE TITLE
Have the bot automatically increase the delay

### ISSUE THREAD

**Issue by PressStartandSelect** [ArchiveTeam/ArchiveBot#145] opened 2015-01-15 02:38 UTC
If ArchiveBot hits too many 5xx or 0 NetworkTimedOut errors in a row (or hits them too frequently), it should automatically increase the delay by 50-200. This would require less user intervention, but may cause problems if a site being archived links to a dead site or a site that blocks ArchiveBot (like vine.co) and should probably be togglable through a command (e.g. !autodelay d0jkf5u0j2d62iqzq2tskn552 off).

**Comment by chfoo** [comment] 2015-01-15 04:08
Possible duplicate of #83? Maybe this issue should be about new `!autodelay`.

**Comment by yipdw** [comment] 2015-01-16 06:15
Yeah, duplicates #83.

**Closed by yipdw** 2015-01-16 06:15 UTC
